<a href="https://colab.research.google.com/github/tejinderpa/Natural-Language-Processing/blob/branch1/text_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
temp_df = pd.read_csv('/content/IMDB Dataset.csv', engine='python')

In [7]:
temp_df.shape

(50000, 2)

In [8]:
df = temp_df

In [9]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [11]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [12]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(418)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [16]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [17]:
df['review'] = df['review'].apply(remove_tags)

In [18]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [19]:
df['review'] = df['review'].apply(lambda x:x.lower())

In [24]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
df

                                                  review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
49995  thought movie right good job. creative origina...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  going disagree previous comment side maltin on...  negative
49999  one expects star trek movies high art, fans ex...  negative

[49582 rows x 2 columns]

In [26]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [27]:
X

                                                  review
0      one reviewers mentioned watching 1 oz episode ...
1      wonderful little production. filming technique...
2      thought wonderful way spend time hot summer we...
3      basically there's family little boy (jake) thi...
4      petter mattei's "love time money" visually stu...
...                                                  ...
49995  thought movie right good job. creative origina...
49996  bad plot, bad dialogue, bad acting, idiotic di...
49997  catholic taught parochial elementary schools n...
49998  going disagree previous comment side maltin on...
49999  one expects star trek movies high art, fans ex...

[49582 rows x 1 columns]

In [28]:
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 49582, dtype: object

In [29]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [30]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [32]:
X_train.shape

(39665, 1)

In [33]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
cv = CountVectorizer()

In [ ]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [ ]:
X_train_bow.shape

(7986, 48282)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [ ]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]], dtype=int64)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8527791687531296

In [ ]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8372558838257386

In [ ]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8407611417125689

## Using TfIdf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [ ]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8482724086129194

In [ ]:
import gensim

In [ ]:
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary=True,limit=500000)

In [ ]:
model['cricket'].shape

(300,)

In [ ]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

In [ ]:
# Remove stopwords

X_train = X_train['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
# Remove stopwords

X_test = X_test['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [ ]:
import spacy
import en_core_web_sm
# Load the spacy model. This takes a few seconds.
nlp = en_core_web_sm.load()
# Process a sentence using the model
doc = nlp(X_train.values[0])
print(doc.vector)

[ 0.15583833  0.22911808  0.13835862 -0.2090293  -0.00363565 -0.13118638
 -0.15676734  0.23040245 -0.24502586 -0.10665981  0.23412983 -0.21705897
  0.13545002  0.13861737  0.12415285  0.21369664 -0.19687523 -0.10246313
 -0.03955808  0.27656794 -0.11084636 -0.28008527  0.3439968   0.0482447
 -0.06924975 -0.03105986 -0.54718924 -0.3975329   0.1704354  -0.16617411
  0.09593288 -0.31931752  0.42519966  0.05527496  0.06130749 -0.3888249
 -0.14431256  0.07848645  0.07683445  0.3278561  -0.3507611  -0.1357377
  0.28880984  0.09166662  0.0593424  -0.04693977  0.1484201   0.01081875
  0.25666746  0.21095097  0.1744978   0.04549917  0.19118404 -0.25923675
 -0.06680956  0.25583443 -0.06317639 -0.2850735  -0.03264944  0.0042502
 -0.07356709 -0.09716224  0.08560921 -0.09941689 -0.12068396 -0.21283795
 -0.03129313 -0.32813746  0.42847297 -0.37240502  0.26251498 -0.11578684
 -0.03221569 -0.05079779  0.17090753 -0.12238634 -0.07934     0.22784583
  0.20331696 -0.5104732   0.07128731 -0.03987676 -0.05812799  0.19840325
 -0.10885198 -0.09540041  0.2161586  -0.17952771  0.04469092  0.06091264
  0.05722181 -0.02751416  0.19805025  0.32649586 -0.06467736  0.10155083]

In [ ]:
input_arr = []
for item in X_train.values:
    doc = nlp(item)
    input_arr.append(doc.vector)

In [ ]:
input_arr = np.array(input_arr)

In [ ]:
input_arr.shape

(7986, 96)

In [ ]:
input_test_arr = []
for item in X_test.values:
    doc = nlp(item)
    input_test_arr.append(doc.vector)

In [ ]:
input_test_arr = np.array(input_test_arr)

In [ ]:
input_test_arr.shape

(1997, 96)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb = GaussianNB()
gnb.fit(input_arr,y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(input_test_arr)
accuracy_score(y_test,y_pred)

0.6119178768152228